joint_1_velocity:
    type: "effort_controllers/JointVelocityController"
    joint: arm_joint_1
    pid: {p: 2.0, i: 100.0, d: 0.0, i_clamp_min: -100.0, i_clamp_max: 100.0, antiwindup: true}

joint_2_velocity:
    type: "effort_controllers/JointVelocityController"
    joint: arm_joint_2
    pid: {p: 1.0, i: 100.0, d: 0.0, i_clamp_min: -100.0, i_clamp_max: 100.0, antiwindup: true}

joint_3_velocity:
    type: "effort_controllers/JointVelocityController"
    joint: arm_joint_3
    pid: {p: 1.0, i: 100.0, d: 0.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0, antiwindup: true}

joint_4_velocity:
    type: "effort_controllers/JointVelocityController"
    joint: arm_joint_4
    pid: {p: 1.0, i: 100.0, d: 0.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0, antiwindup: true}

joint_5_velocity:
    type: "effort_controllers/JointVelocityController"
    joint: arm_joint_5
    pid: {p: 5.0, i: 100.0, d: 0.0, i_clamp_min: -100.0, i_clamp_max: 100.0, antiwindup: true}
