arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gains:
    arm_joint_1: {p: 1000.0, i: 0.01, d: 0.1}
    arm_joint_2: {p: 1000.0, i: 0.01, d: 0.1}
    arm_joint_3: {p: 1000.0, i: 0.01, d: 0.1}
    arm_joint_4: {p: 1000.0, i: 0.01, d: 0.1}
    arm_joint_5: {p: 1000.0, i: 0.01, d: 0.1}
  constraints:
    goal_time: 0.6
    arm_joint_1:
      goal: 0.1
    arm_joint_2:
      goal: 0.1
    arm_joint_3:
      goal: 0.1
    arm_joint_4:
      goal: 0.1
    arm_joint_5:
      goal: 0.1
